apiVersion: apps/v1
kind: Deployment
metadata:
  name: functional-validation-service-deployment
  labels:
    app: functional-validation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: functional-validation-service
  template:
    metadata:
      labels:
        app: functional-validation-service
    spec:
      containers:
      - name: functional-validation-service
        image: gcr.io/devenv-215523/functional-validation-service:${SERVICE_VERSION}
        env:
          - name: POSTGRES_SCHEMA
            value: "${DB_SCHEMA}"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: genes-db-credentials
                key: username
          - name: PGPW
            valueFrom:
              secretKeyRef:
                name: genes-db-credentials
                key: password
          - name: POSTGRES_DB
            value: "genes-db"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=devenv-215523:us-east1:genes-instance=tcp:5432",
                  "-credential_file=/secrets/cloudsql/staging-service-account.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: service-account-key
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: service-account-key
          secret:
            secretName: service-account-key
---
apiVersion: v1
kind: Service
metadata:
  name: functional-validation-service-service
  labels:
    app: functional-validation-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: functional-validation-service
