#!/bin/bash
GCR_PROJECT_ID=devenv-215523
SERVICE_DOCKER_IMAGE_NAME=functional-validation-service
IMPORTER_DOCKER_IMAGE_NAME=functional-validation-importer
KUBE_DEPLOYMENT_NAME=functional-validation-service-deployment
KUBE_DEPLOYMENT_CONTAINER_NAME=functional-validation-service
