#
# docker compose file for testing
#

version: '3'
services:

  # database
  graphqlservice_postgrestest_1:
    image: postgres:latest    
    ports:
      - 5555:5432 # don't conflict with local posgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
