#
# docker compose file for testing
#

version: '3'
services:

  # database
  postgrestest:
    image: postgres:latest
    container_name: graphqlservice_postgrestest_1
    ports:
      - 5555:5432 # don't conflict with local posgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
