name: Test

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v2
        
      - name: Test importer
        run: |
          importer/scripts/test.sh
          
      - name: Test service
        run: |
          graphqlservice/scripts/test.sh
